export const REQUERST_SIGNUP = 'REQUERST_SIGNUP'
export const LOAD_SIGNUP = 'LOAD_SIGNUP'
export  const SUCCESS_SIGNUP = 'SUCCESS_SIGNUP'
export const ERROR_SIGNUP = 'ERROR_SIGNUP' 

export const REQUERST_SESSION = 'REQUERST_SESSION'
export const LOAD_SESSION = 'LOAD_SESSION'
export  const SUCCESS_SESSION = 'SUCCESS_SESSION'
export const ERROR_SESSION = 'ERROR_SESSION' 

export const REQUERST_LOGIN = 'REQUERST_LOGIN'
export const LOAD_LOGIN = 'LOAD_LOGIN'
export  const SUCCESS_LOGIN = 'SUCCESS_LOGIN'
export const ERROR_LOGIN = 'ERROR_LOGIN' 


export const REQUERST_USER_UPDATE = 'REQUERST_USER_UPDATE'
export const LOAD_USER_UPDATE = 'LOAD_USER_UPDATE'
export  const SUCCESS_USER_UPDATE_DATA = 'SUCCESS_USER_UPDATE_DATA'
export const ERROR_USER_UPDATE_DATA = 'ERROR_USER_UPDATE_DATA' 

export const REQUERST_SESSION_DATA = 'REQUERST_SESSION_DATA'
export const LOAD_SESSION_DATA = 'LOAD_SESSION_DATA'
export  const SUCCESS_SESSION_DATA = 'SUCCESS_SESSION_DATA'
export const ERROR_SESSION_DATA = 'ERROR_SESSION_DATA' 


export const REQUERST_SESSION_DATA_UPDATE = 'REQUERST_SESSION_DATA_UPDATE'
export const LOAD_SESSION_DATA_UPDATE = 'LOAD_SESSION_DATA_UPDATE'
export  const SUCCESS_SESSION_DATA_UPDATE = 'SUCCESS_SESSION_DATA_UPDATE'
export const ERROR_SESSION_DATA_UPDATE = 'ERROR_SESSION_DATA_UPDATE' 



